[project]
name = "big-bear-demo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = ["azure-storage-blob", "graphviz", "polars", "polars-h3", "h3"]
